// Public article; research and reviewed Markdown remain in the local editorial workspace.
export function ArticleContent() {
  return <>
    <p>Ein DATEV-Export aus der Zeiterfassung bereitet Arbeitsstunden für die Übergabe an das Lohnbüro vor. In Quoska kannst du monatliche Netto-Arbeitsstunden als Datei für <strong>DATEV LODAS</strong> herunterladen. Der Export ist ohne Aufpreis in allen Tarifen enthalten, auch im kostenlosen Tarif bis drei Personen. <a href="#quelle-quoska">Quoska: Funktionsumfang</a></p>
    <h2 id="abschnitt-1">Was bringt ein DATEV-Export am Monatsende?</h2>
    <p>Wenn du Arbeitszeiten digital erfasst, liegen Beginn, Ende und Pausen bereits vor. Für die Lohnvorbereitung ist dann vor allem wichtig, welche Stunden zu welcher Person und welchem Monat gehören. Eine passende Importdatei kann dem Lohnbüro das erneute Abtippen der Stundensummen ersparen. Ob dieser Weg für deinen Betrieb passt, hängt vom verwendeten Lohnprogramm und der vereinbarten Abrechnung ab.</p>
    <p>DATEV bietet für den Dateiaustausch eine ASCII-Schnittstelle an. Darüber lassen sich entsprechend aufgebaute TXT- oder CSV-Dateien in die DATEV-Payroll übernehmen. Eine beliebige Tabelle wird durch die Dateiendung allein noch nicht zur passenden Importdatei. <a href="#quelle-datev">DATEV: Schnittstellen zur Payroll</a></p>
    <p>Der praktische Vorteil eines festen Exportablaufs: Du prüfst die Stunden vor der Übergabe, verwendest die vereinbarten Personalnummern und kannst festhalten, welchen Monatsstand du weitergegeben hast. Eine Zeitersparnis in Minuten oder eine fehlerfreie Lohnabrechnung lässt sich daraus nicht pauschal versprechen.</p>
    <h2 id="abschnitt-2">Was enthält der kostenlose Quoska-Export?</h2>
    <p>Quoska summiert abgeschlossene Zeiteinträge abzüglich der erfassten Pausen. Pro eingeschlossener Person, Monat und zugeordneter Lohnart entsteht eine Stundenbuchung. Die Monatssumme wird erst nach dem Zusammenrechnen auf zwei Nachkommastellen gerundet. Exportiert werden Zahlen und Zuordnungen, keine Mitarbeiternamen oder Eintragsnotizen. <a href="#quelle-quoska">Quoska: Funktionsumfang</a></p>
    <p><strong>Fiktives Beispiel:</strong> Eine Mitarbeiterin hat zwei abgeschlossene Einträge mit jeweils 8 Stunden 30 Minuten Anwesenheit und 30 Minuten Pause. Der Export enthält für diese beiden Einträge zusammen 16,00 Arbeitsstunden. Daraus entsteht noch kein Auszahlungsbetrag: Stundensatz und Abrechnungsregeln gehören in die Lohnabrechnung.</p>
    <p>Enthalten sind die tatsächlich erfassten Netto-Arbeitsstunden. Vergütung für Urlaub, Krankheit und Feiertage, Zuschläge, Überstundenauszahlungen, Kostenstellen und rückwirkende Abrechnungskorrekturen werden in dieser Version nicht berechnet oder exportiert. Unterstützt wird DATEV LODAS; für DATEV „Lohn und Gehalt“ ist diese Datei nicht vorgesehen. <a href="#quelle-quoska">Quoska: Funktionsumfang</a></p>
    <p>Die Tarife unterscheiden sich weiterhin nach Teamgröße. Der Export selbst kostet in Quoska nichts zusätzlich. Welche Personenzahl dein Tarif abdeckt, steht auf der <a href="/preise">Preisseite</a>. Kosten des Lohnbüros und der dort verwendeten DATEV-Software sind darin nicht enthalten.</p>
    <h2 id="abschnitt-3">Diese Angaben klärst du mit deinem Lohnbüro</h2>
    <p>Vor der ersten Einrichtung reichen wenige konkrete Angaben. Du kannst sie auch schriftlich erfragen:</p>
    <ul><li>Verwendet das Lohnbüro für deinen Betrieb DATEV LODAS?</li><li>Welche Beraternummer und Mandantennummer sollen in der Datei stehen?</li><li>Welche DATEV-Personalnummer gehört zu welcher Person?</li><li>Welche Lohnart soll die Arbeitsstunden erhalten, und für welche Personen ist diese Stundenbuchung gewünscht?</li><li>Welcher Monat soll übergeben werden, und wurden dafür schon Stunden übernommen?</li></ul>
    <p>Bei festem Monatsgehalt sollte ausdrücklich geklärt sein, wofür die übergebenen Stunden verwendet werden. Sie sollen nicht versehentlich eine zusätzliche Auszahlung auslösen. Quoska wählt deshalb keine Standard-Lohnart für dich aus. Personen können ausdrücklich vom Stundenexport ausgeschlossen werden. <a href="#quelle-quoska">Quoska: Funktionsumfang</a></p>
    <h2 id="abschnitt-4">So bereitest du den Monat in Quoska vor</h2>
    <p><strong>Zuordnung speichern:</strong> Als Administrator öffnest du <strong>Berichte → DATEV</strong>. Hinterlege die Angaben aus dem Lohnbüro und entscheide pro Person, ob ihre Stunden exportiert werden sollen.</p>
    <p><strong>Monat auswählen und prüfen:</strong> Wähle ein Datum im gewünschten Abrechnungsmonat. Die Vorschau wertet den ganzen Kalendermonat aus. Prüfe zusätzlich, ob alle erwarteten Arbeitstage erfasst sind. Fehlende Tage werden nicht automatisch als Arbeitszeit ergänzt.</p>
    <p><strong>Offene Punkte erledigen:</strong> Der Export blockiert unter anderem bei offenen Zeiteinträgen, offenen Korrekturanfragen für enthaltene Einträge, fehlenden Zuordnungen und Einträgen über eine Monatsgrenze. Bereits importierte Zeiten können enthalten sein; ein Hinweis erinnert an die Prüfung, ob diese schon im Lohnprogramm gebucht wurden. <a href="#quelle-quoska">Quoska: Funktionsumfang</a></p>
    <p><strong>Datei herunterladen und übergeben:</strong> Bestätige die geprüfte Vorschau und lade die LODAS-Datei herunter. Verwende den mit deinem Lohnbüro vereinbarten Übertragungsweg. Stimme Person, Monat, Lohnart und Stundensumme mit dem Lohnbüro ab.</p>
    <p><strong>Erneute Übergaben abstimmen:</strong> Nach einer Änderung im Monat solltest du nicht einfach eine zweite Datei nachreichen. Kläre, ob die bisherige Buchung ersetzt oder korrigiert werden muss. Quoska zeigt vorhandene Exportstände an, kann aber nicht feststellen, welche Datei dein Lohnbüro bereits importiert hat. <a href="#quelle-quoska">Quoska: Funktionsumfang</a></p>
    <p>Für einen nachvollziehbaren Ausgangsbestand hilft der Ratgeber zum <a href="/arbeitszeitnachweis">Arbeitszeitnachweis</a>. Wenn du noch mit der Erfassung beginnst, erklärt der Beitrag zur <a href="/digitale-zeiterfassung">digitalen Zeiterfassung</a> den täglichen Ablauf.</p>
    <h2 id="abschnitt-5">Dateiexport oder direkte DATEV-Verbindung?</h2>
    <p>Beim Dateiexport lädst du die Datei herunter und gibst sie an das Lohnbüro weiter. Eine direkte Anbindung über den DATEV Lohnimportdatenservice übermittelt Daten dagegen über das DATEV-Rechenzentrum an die Lohnprogramme. DATEV beschreibt auch diesen Weg als Übergabe von Stamm- und Bewegungsdaten für die Gehaltsabrechnung. <a href="#quelle-datev-cloud">DATEV: Prozessgrafik</a></p>
    <p>Quoska bietet hier den Dateiexport an. Es erfolgt keine direkte Übertragung an DATEV. Auch nach dem Download bleiben die erfassten Zeiten bearbeitbar; der Export ist weder ein gesperrter Monatsabschluss noch eine Bestätigung des Imports. <a href="#quelle-quoska">Quoska: Funktionsumfang</a></p>
    <p>Wenn dein Lohnbüro mit LODAS arbeitet und monatliche Arbeitsstunden übernehmen möchte, kannst du die Monatsübergabe in Quoska vorbereiten. <a href="https://quoska.de/register">Kostenlos mit Quoska starten</a> oder als Administrator den <a href="https://quoska.de/app/reports?tab=datev">DATEV-Export öffnen</a>.</p>
  </>;
}
