import Link from "next/link";
import type { Metadata } from "next";
import { MarketingPageShell } from "@/components/marketing/page-shell";
export const metadata: Metadata = {"title": "Ersatzruhetag nach Sonntags- oder Feiertagsarbeit planen", "description": "Zwei oder acht Wochen? Beispiele zeigen, wie Ersatzruhetage nach Sonn- und Feiertagsarbeit mit dem Beschäftigungstag und der Ruhezeit zusammenpassen.", "alternates": {"canonical": "/ratgeber/ersatzruhetag-sonntag-feiertag-planen"}};
export default function GuidePage() { return (<MarketingPageShell eyebrow="Ratgeber und Checklisten" title={"Ersatzruhetag nach Sonntags- oder Feiertagsarbeit planen"} intro={"Nach Sonntagsarbeit sieht die Grundregel einen Ersatzruhetag innerhalb eines zweiwöchigen Zeitraums vor; bei Arbeit an einem werktäglichen Feiertag sind es acht Wochen. Der Beschäftigungstag zählt jeweils zum Zeitraum. Prüfe deshalb neben der Lage des freien Tages auch die angrenzenden Schichten und die tägliche Ruhezeit. Die folgenden Beispiele erläutern diesen Prüfweg für bereits zulässige Beschäftigung."} cta={false}><article className="mx-auto max-w-5xl px-5 py-10 sm:px-6 space-y-8 [&_h2]:font-serif [&_h2]:text-3xl [&_p]:my-4 [&_p]:leading-7 [&_ul]:list-disc [&_ul]:pl-6 [&_a]:underline [&_a]:text-[#5145ad]" style={{overflowWrap:"anywhere"}}>
<Link href="/ratgeber">Alle Ratgeber und Checklisten</Link>
<section><h2>{"Zuerst klären: Sonntag oder werktäglicher Feiertag?"}</h2>
<p>{"Dieser Ratgeber behandelt erwachsene Beschäftigte in Deutschland im allgemeinen Anwendungsbereich des Arbeitszeitgesetzes. Vorausgesetzt wird, dass die Sonn- oder Feiertagsbeschäftigung zulässig ist. Sonderregelungen, Vergütung, Zuschläge und eine vollständige Dienstplanprüfung sind nicht Gegenstand. Allgemeine Information, keine individuelle Rechtsberatung."}</p>
<p>{"§ 9 ArbZG untersagt grundsätzlich die Beschäftigung an Sonntagen und gesetzlichen Feiertagen von 0 bis 24 Uhr. Ein geplanter Ersatzruhetag ist für sich keine Erlaubnis zur Beschäftigung; die Zulässigkeit muss gesondert geklärt sein."}</p>
<p>{"Nach § 11 Absatz 3 gilt für Sonntagsarbeit ein zweiwöchiger Zeitraum, für Arbeit an einem auf einen Werktag fallenden Feiertag ein achtwöchiger Zeitraum. In beiden Fällen muss dieser Zeitraum den Beschäftigungstag einschließen."}</p>
<p>{"Beginne mit dem tatsächlichen Einsatzdatum, nicht mit der Monatsabrechnung. Halte daneben fest, ob du Sonntagsarbeit oder Arbeit an einem werktäglichen gesetzlichen Feiertag prüfst. Ist schon die Feiertagseigenschaft am maßgeblichen Ort unklar, bleibt die Auswahl des Prüfwegs offen. Dieser Text enthält keinen regionalen Feiertagskalender."}</p>
<p>Belege: <a href={"https://www.gesetze-im-internet.de/arbzg/BJNR117100994.html"}>{"Arbeitszeitgesetz: Ruhezeit und Sonn- und Feiertagsausgleich"}</a></p>
</section>
<section><h2>{"Zwei Kalenderbeispiele: Der Beschäftigungstag zählt mit"}</h2>
<p>{"Die Beispiele verwenden bewusst relative Kalendertage statt eines bestimmten Feiertags. Sie setzen keine abweichende Regelung voraus. Der Zeitraum beginnt jeweils als ausdrückliche Rechenannahme mit dem Beschäftigungstag; damit wird nicht behauptet, dass das Gesetz stets genau diesen Beginn festlegt."}</p>
<p>{"Beispiel Sonntag: Setze den Beschäftigungssonntag als Tag 1 eines gewählten Zwei-Wochen-Zeitraums. Tag 14 ist dann der Samstag der übernächsten Kalenderwoche. Ein vorgesehener Ersatzruhetag am Freitag, Tag 13, liegt innerhalb dieses Fensters; der folgende Montag, Tag 16, liegt außerhalb."}</p>
<p>{"Beispiel werktäglicher Feiertag: Setze einen angenommenen gesetzlichen Feiertag an einem Montag als Tag 1. Ein Acht-Wochen-Zeitraum umfasst dann die Tage 1 bis 56. Ein vorgesehener Ersatzruhetag an Tag 40 liegt innerhalb dieses Fensters; Tag 57 liegt außerhalb."}</p>
<p>{"Beide Beispiele zeigen nur die Lage im jeweils gewählten Zeitfenster. Ein darin liegender Tag ist noch nicht vollständig geprüft: Seine tatsächliche Beschäftigungsfreiheit und die Verbindung zur Ruhezeit kommen hinzu. Die Beispiele bestimmen auch keine allgemeine späteste Frist für jeden denkbaren Dienstplan."}</p>
<p>{"Als eigene Planungshilfe empfiehlt sich eine Zuordnung je geprüftem Einsatz: Beschäftigungstag, Art des Tages, Anfang und Ende des verwendeten Zeitfensters sowie vorgesehener Ersatzruhetag. So wird sichtbar, auf welchen Einsatz sich eine freie Zeit beziehen soll. Bei mehreren Einsätzen ist eine einzelne pauschale Monatsnotiz weniger nachvollziehbar."}</p>
<p>Belege: <a href={"https://www.gesetze-im-internet.de/arbzg/BJNR117100994.html"}>{"Arbeitszeitgesetz: Ruhezeit und Sonn- und Feiertagsausgleich"}</a></p>
</section>
<section><h2>{"Den freien Tag zusammen mit den Nachbarschichten betrachten"}</h2>
<p>{"Nach § 5 Absatz 1 beträgt die tägliche ununterbrochene Ruhezeit grundsätzlich mindestens elf Stunden. § 11 Absatz 4 verlangt, den Ersatzruhetag unmittelbar mit einer Ruhezeit nach § 5 zu verbinden, soweit keine technischen oder arbeitsorganisatorischen Gründe entgegenstehen."}</p>
<p>{"Für das folgende fiktive Beispiel ist ein vollständig beschäftigungsfreier Dienstag vorgesehen. Es gibt keine Zeitumstellung, keine Unterbrechung, keine abweichende Ruhezeitregel und keine entgegenstehenden technischen oder arbeitsorganisatorischen Gründe. Die Lage innerhalb des Ersatzruhefensters wird als bereits geprüft vorausgesetzt."}</p>
<p>{"Variante A: Die letzte Arbeit endet am Montag um 13 Uhr. Bis Dienstag um 0 Uhr liegen elf ununterbrochene Stunden. Es folgt der vollständig freie Dienstag; die nächste Arbeit beginnt am Mittwoch um 6 Uhr. Damit lässt sich in diesem Beispiel eine elfstündige Ruhezeit unmittelbar vor dem freien Tag abgrenzen."}</p>
<p>{"Variante B: Die letzte Arbeit endet erst am Montag um 20 Uhr, die nächste beginnt am Mittwoch um 6 Uhr. Vor dem freien Dienstag liegen nur vier, danach nur sechs Stunden. Obwohl der Dienstag frei ist, zeigt dieser Plan keine unmittelbar davor oder danach liegende elfstündige Ruhezeit. Unter den getroffenen Annahmen erfüllt diese Anordnung die erläuterte Verbindung nicht."}</p>
<p>{"Der Unterschied liegt nicht im markierten Dienstag, sondern in den angrenzenden Arbeitszeiten. Prüfe deshalb immer das tatsächliche Ende vor und den tatsächlichen Beginn nach dem vorgesehenen freien Tag. Ein später geändertes Schichtende ist Anlass, die Zuordnung erneut zu prüfen. Bei Unterbrechungen oder Sonderregeln ist eine gesonderte Beurteilung nötig."}</p>
<p>Belege: <a href={"https://www.gesetze-im-internet.de/arbzg/BJNR117100994.html"}>{"Arbeitszeitgesetz: Ruhezeit und Sonn- und Feiertagsausgleich"}</a></p>
</section>
<section><h2>{"Was die Prüfung abschließt – und was offenbleibt"}</h2>
<p>{"§ 12 ArbZG ermöglicht unter bestimmten Voraussetzungen tarifliche oder tarifgestützte Abweichungen. Für auf Werktage fallende Feiertage kann insbesondere der Wegfall von Ersatzruhetagen oder eine Beschäftigungsfreistellung innerhalb eines festzulegenden Ausgleichszeitraums vereinbart werden."}</p>
<p>{"Wenn ihr euch auf eine Abweichung beruft, sollte die konkrete Regelung mit ihrem Geltungsbereich zur Prüfung vorliegen. Ohne diese Unterlage sollte der Sonderfall nicht anhand der Standardbeispiele als erledigt markiert werden."}</p>
<p>{"Die Grundregel des § 11 Absatz 1 verlangt außerdem mindestens 15 beschäftigungsfreie Sonntage im Jahr. Das ist eine eigene Jahresprüfung neben der Zuordnung einzelner Ersatzruhetage; zulässige Abweichungen sind gesondert zu beurteilen."}</p>
<p>{"Der nächste praktische Schritt ist eine Gegenüberstellung des vorgesehenen Ersatzruhetags mit den tatsächlichen Zeitaufzeichnungen der angrenzenden Einsätze. Halte eine noch offene Beschäftigungserlaubnis, unklare Feiertagseigenschaft oder ungeprüfte Sonderregel ausdrücklich als offen fest, statt aus einer passenden Kalenderrechnung auf einen insgesamt zulässigen Dienstplan zu schließen."}</p>
<p>{"Für die nachvollziehbare Darstellung von Beginn, Ende und Korrekturen führt der Leitfaden zum Arbeitszeitnachweis weiter. Wenn ihr die tägliche Erfassung erst einrichtet, erläutert die Einführung in digitale Zeiterfassung den Produktablauf. Diese Links dienen der Dokumentation; eine automatische Ersatzruhetagsprüfung durch Quoska wird hier nicht vorausgesetzt."}</p>
<p>Belege: <a href={"https://www.gesetze-im-internet.de/arbzg/BJNR117100994.html"}>{"Arbeitszeitgesetz: Ruhezeit und Sonn- und Feiertagsausgleich"}</a></p>
</section>
<section><h2>Passend dazu</h2><ul><li><a href={"https://quoska.de/arbeitszeitnachweis"}>{"Arbeitszeitnachweise nachvollziehbar darstellen"}</a></li><li><a href={"https://quoska.de/digitale-zeiterfassung"}>{"Tägliche Zeiterfassung im Team einrichten"}</a></li></ul></section>
<section><h2>Quellen und weitere Informationen</h2><ul><li><a href={"https://www.gesetze-im-internet.de/arbzg/BJNR117100994.html"}>{"Arbeitszeitgesetz: Ruhezeit und Sonn- und Feiertagsausgleich"}</a></li></ul></section>
</article></MarketingPageShell>); }
