-- Local/test database only. All fixtures and preference changes are rolled back.
BEGIN;
INSERT INTO auth.users(id,email,email_confirmed_at) VALUES
 ('38000000-0000-4000-8000-000000000001','admin-contact-a@example.test',now()),
 ('38000000-0000-4000-8000-000000000002','admin-contact-b@example.test',now()),
 ('38000000-0000-4000-8000-000000000003','admin-contact-employee@example.test',now()),
 ('38000000-0000-4000-8000-000000000004','admin-contact-unconfirmed@example.test',NULL);
INSERT INTO public.tenants(id,name) VALUES ('38000000-0000-4000-8000-000000000010','Consent SQL test');
INSERT INTO public.employees(id,user_id,tenant_id,first_name,last_name,email,role) VALUES
 ('38000000-0000-4000-8000-000000000011','38000000-0000-4000-8000-000000000001','38000000-0000-4000-8000-000000000010','A','Test','admin-contact-a@example.test','admin'),
 ('38000000-0000-4000-8000-000000000012','38000000-0000-4000-8000-000000000002','38000000-0000-4000-8000-000000000010','B','Test','admin-contact-b@example.test','admin'),
 ('38000000-0000-4000-8000-000000000013','38000000-0000-4000-8000-000000000003','38000000-0000-4000-8000-000000000010','C','Test','admin-contact-employee@example.test','employee'),
 ('38000000-0000-4000-8000-000000000014','38000000-0000-4000-8000-000000000004','38000000-0000-4000-8000-000000000010','D','Test','admin-contact-unconfirmed@example.test','admin');
SELECT set_config('request.jwt.claim.sub','38000000-0000-4000-8000-000000000001',true);
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 ASSERT public.get_admin_contact_preference() = '{"enabled":false,"eligible":false,"canEnable":true}'::jsonb;
 PERFORM public.set_admin_contact_preference(false,'admin-checkin-v1','settings');
 ASSERT (SELECT count(*) FROM public.admin_contact_events) = 0;
 ASSERT (public.set_admin_contact_preference(true,'admin-checkin-v1','setup')->>'eligible')::boolean;
 PERFORM public.set_admin_contact_preference(true,'admin-checkin-v1','setup');
 ASSERT (SELECT count(*) FROM public.admin_contact_events) = 1, 'retry created duplicate';
 ASSERT (SELECT created_at=now() FROM public.admin_contact_events), 'timestamp not generated by database';
 BEGIN
  UPDATE public.admin_contact_events SET enabled=false;
  RAISE EXCEPTION 'direct edit allowed';
 EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN
  PERFORM public.set_admin_contact_preference(true,'forged-version','setup');
  RAISE EXCEPTION 'wrong version allowed';
 EXCEPTION WHEN invalid_parameter_value THEN NULL; END;
END $$;
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','38000000-0000-4000-8000-000000000002',true);
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 ASSERT (SELECT count(*) FROM public.admin_contact_events) = 0, 'cross-account history exposed';
 ASSERT NOT (public.get_admin_contact_preference()->>'enabled')::boolean;
END $$;
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','38000000-0000-4000-8000-000000000003',true);
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 BEGIN
  PERFORM public.set_admin_contact_preference(true,'admin-checkin-v1','settings');
  RAISE EXCEPTION 'employee enrolled';
 EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','38000000-0000-4000-8000-000000000004',true);
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 BEGIN
  PERFORM public.set_admin_contact_preference(true,'admin-checkin-v1','setup');
  RAISE EXCEPTION 'unconfirmed account enrolled';
 EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','38000000-0000-4000-8000-000000000001',true);
UPDATE auth.users SET email='changed@example.test' WHERE id=auth.uid();
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 ASSERT NOT (public.get_admin_contact_preference()->>'eligible')::boolean, 'email change reused consent';
 ASSERT (public.set_admin_contact_preference(true,'admin-checkin-v1','settings')->>'eligible')::boolean;
 ASSERT (SELECT count(*) FROM public.admin_contact_events)=2;
END $$;
RESET ROLE;
UPDATE auth.users SET banned_until=now()+interval '1 day' WHERE id=auth.uid();
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 ASSERT NOT (public.get_admin_contact_preference()->>'eligible')::boolean, 'banned admin eligible';
 BEGIN
  PERFORM public.set_admin_contact_preference(true,'admin-checkin-v1','settings');
  RAISE EXCEPTION 'banned account enrolled';
 EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
UPDATE auth.users SET banned_until=NULL WHERE id=auth.uid();
UPDATE public.employees SET role='employee' WHERE user_id=auth.uid();
SET LOCAL ROLE authenticated;
DO $$ BEGIN
 ASSERT NOT (public.get_admin_contact_preference()->>'eligible')::boolean, 'stale admin role trusted';
 ASSERT NOT (public.set_admin_contact_preference(false,'admin-checkin-v1','settings')->>'enabled')::boolean;
 ASSERT (SELECT count(*) FROM public.admin_contact_events)=3, 'withdrawal missing';
 PERFORM public.set_admin_contact_preference(false,'admin-checkin-v1','settings');
 ASSERT (SELECT count(*) FROM public.admin_contact_events)=3, 'duplicate withdrawal';
END $$;
RESET ROLE;
DELETE FROM auth.users WHERE id='38000000-0000-4000-8000-000000000001';
DO $$ BEGIN ASSERT (SELECT count(*) FROM public.admin_contact_events)=0, 'erasure failed'; END $$;
SET LOCAL ROLE anon;
DO $$ BEGIN
 BEGIN
  PERFORM public.get_admin_contact_preference();
  RAISE EXCEPTION 'anonymous RPC permitted';
 EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
ROLLBACK;
